### ISSUE TITLE
Packaging and module declarations and references in /Dist

### ISSUE THREAD

**Issue by amccubbin** [formio/ng2-formio#50]
Issues with atom-typescript recognizing import:
```
import { FormioModule }  from 'ng2-formio';
```
Also get typescript error when transpiling. 
```
error TS2307: Cannot find module 'ng2-formio'.
```
Properly recognizes if using the following import:
```
import { FormioModule }  from 'ng2-formio/dist/index';
```
However, systemjs does not properly find dependencies if importing this way when building in development. 

When trying to bundle for production build
```
Error on dependency parsing for ng2-bootstrap/bundles/ng2-bootstrap.umd.js at file:///home/dev/web/.../node_modules/ng2-bootstrap/bundles/ng2-bootstrap.umd.js
	Loading ng2-formio/dist/formio.js
	Loading ng2-formio
	Loading dist/tmp/app/shared/call/call.module.js
	Loading dist/tmp/app/shared/shared.module.js
	Loading dist/tmp/app/app.module.js
	Loading dist/tmp/app/main.js
	Error: Multiple anonymous defines.
```
There is an issue with the way the dist/index.js is exporting the module and/or the dependency of formio.js. Typescript and subsequently systemjs isn't picking up the module or dependency references properly. 

Using build system from https://github.com/mgechev/angular-seed

**Comment by amccubbin** [comment]
Dependency issues were solved by adding necessary paths to various packages in systemjs configuration as would be expected. But the need to import from 'ng2-formio/dist/index' seems odd.

**Comment by travist** [comment]
I am having a hard time figuring out what is different from the people who are saying there is an issue with the packaging vs. getting Form.io into something like [ng-admin](https://github.com/formio/ng-admin) which I did not need to refer to the full path. 

I am open to suggestions from anyone in the community who would like to help out with this.

**Comment by pkt-zer0** [comment]
Things worked fine with v0.5.0, I'm guessing something changed with [this commit](https://github.com/formio/ng2-formio/commit/fc2973b62d92378c87aaf93a52d04e907cd660f3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) . There used to be a "typings" entry in package.json, which would be needed here ([AFAIK](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)).

Readding the "types"/"typings" field alone was not enough to fix it, though. Afterwards, the import from plain "ng2-formio" (no "/dist/index") works, but I get a compilation error.

    ERROR in ./~/formiojs/src/providers/storage/url.js
    Module not found: Error: Can't resolve '../../Formio' in '/path/to/project/node_modules/formiojs/src/providers/storage'
    @ ./~/formiojs/src/providers/storage/url.js 2:14-37
    @ ./~/formiojs/src/providers/storage/index.js
    @ ./~/formiojs/src/providers/index.js
    @ ./~/formiojs/src/formio.js
    @ ./~/ng2-formio/dist/formio.service.js
    @ ./~/ng2-formio/dist/formio.component.js
    @ ./~/ng2-formio/dist/formio.js
    @ ./~/ng2-formio/dist/index.js
    @ ./src/app/app.module.ts
    @ ./src/main.ts
    @ multi main

Not sure how much that helps, but it's a start, at least. TypeScript version differences could also be another reason.

**Comment by travist** [comment]
Thank you so much @pkt-zer0. I just resolved the issue with formio.js with version 1.5.3. I will add the typings entry within package.json and see if that fixes the problem.

**Comment by travist** [comment]
So, I just released version 0.9.3 with this fix in place. Let me know if that works for you guys.

**Comment by pkt-zer0** [comment]
The issue with @types/jasmine breaking the build (unless locked to 2.5.41) is still there. (You might need to delete node_modules to reproduce this) Otherwise it works now, thanks!
